export const container: string;
export const listContainer: string;
export const tableHeader: string;
export const contentHeading: string;
export const authorHeading: string;
export const itemsContainer: string;
export const cardListItem: string;
export const listItemContent: string;
export const listItemAuthor: string;
